use super::{FFT64CIPortable, FFT64Portable, NTT4x30CIPortable, NTT4x30Portable};
use poulpy_core::{impl_gglwe_product_digits_strided_reference, impl_glwe_tensoring_reference};

impl_glwe_tensoring_reference!(FFT64Portable);
impl_glwe_tensoring_reference!(NTT4x30Portable);
impl_glwe_tensoring_reference!(FFT64CIPortable);
impl_glwe_tensoring_reference!(NTT4x30CIPortable);
impl_gglwe_product_digits_strided_reference!(FFT64Portable);
impl_gglwe_product_digits_strided_reference!(NTT4x30Portable);
impl_gglwe_product_digits_strided_reference!(FFT64CIPortable);
impl_gglwe_product_digits_strided_reference!(NTT4x30CIPortable);

crate::impl_cpu_core_defaults!(super::FFT64Portable, fft64);
::poulpy_core::impl_conversion_reference_full!(super::FFT64Portable);
::poulpy_core::impl_glwe_packing_derived_full!(super::FFT64Portable);
::poulpy_core::impl_glwe_rotate_reference_full!(super::FFT64Portable);
::poulpy_core::impl_ggsw_rotate_derived_full!(super::FFT64Portable);
::poulpy_core::impl_glwe_mul_xp_minus_one_reference_full!(super::FFT64Portable);
::poulpy_core::impl_glwe_trace_derived_full!(super::FFT64Portable);
::poulpy_core::impl_glwe_ci_conversion_reference_full!(super::FFT64Portable);
crate::impl_cpu_core_defaults!(super::NTT4x30Portable, ntt4x30);
::poulpy_core::impl_conversion_reference_full!(super::NTT4x30Portable);
::poulpy_core::impl_glwe_packing_derived_full!(super::NTT4x30Portable);
::poulpy_core::impl_glwe_rotate_reference_full!(super::NTT4x30Portable);
::poulpy_core::impl_ggsw_rotate_derived_full!(super::NTT4x30Portable);
::poulpy_core::impl_glwe_mul_xp_minus_one_reference_full!(super::NTT4x30Portable);
::poulpy_core::impl_glwe_trace_derived_full!(super::NTT4x30Portable);
::poulpy_core::impl_glwe_ci_conversion_reference_full!(super::NTT4x30Portable);
crate::impl_cpu_core_defaults!(super::FFT64CIPortable, fft64);
crate::impl_cpu_core_defaults!(super::NTT4x30CIPortable, ntt4x30);
