//! Ciphertext, key, plaintext, and secret-key layout types.
//!
//! This module defines the in-memory representations for every
//! cryptographic object manipulated by `poulpy-core`. Types are
//! organised into three sub-layers:
//!
//! * **Standard** (this module) -- serialisable, platform-independent
//!   byte layouts backed by [`poulpy_hal::layouts::VecZnx`] /
//!   [`poulpy_hal::layouts::MatZnx`].
//! * **[`compressed`]** -- seed-compressed variants that store only
//!   the body; the mask is regenerated from a 32-byte PRNG seed.
//! * **[`prepared`]** -- DFT-domain representations tied to a
//!   specific [`poulpy_hal::layouts::Backend`], used for fast
//!   polynomial multiplication.
//!
//! # Parameter newtypes
//!
//! Domain-specific quantities are wrapped in [`u32`]-backed newtypes
//! generated by the `newtype_u32!` macro:
//!
//! | Type | Meaning |
//! |---|---|
//! | [`Degree`] | Ring polynomial degree *N* (always a power of two) |
//! | [`Base2K`] | Base-2 logarithm of the limb radix used in the CRT/digit decomposition |
//! | [`TorusPrecision`] | Total number of precision bits over the torus *T = R/Z* |
//! | [`Rank`] | GLWE rank (number of mask polynomials; 0 for plain LWE) |
//! | [`Dnum`] | Number of gadget-decomposition digits |
//! | [`Dsize`] | Size (in limbs) of each gadget digit |

#[macro_use]
mod macros;

mod diagonals;
mod gglwe;
mod gglwe_to_ggsw_key;
mod ggsw;
mod glwe;
mod glwe_automorphism_key;
mod glwe_plaintext;
mod glwe_public_key;
mod glwe_secret;
mod glwe_secret_tensor;
mod glwe_switching_key;
mod glwe_tensor;
mod glwe_tensor_key;
mod glwe_to_lwe_key;
mod linear_transformation;
mod lwe;
mod lwe_matrix;
mod lwe_plaintext;
mod lwe_secret;
mod lwe_switching_key;
mod lwe_to_glwe_key;
mod polynomial_evaluation;
mod scratch_views;

pub mod compressed;
pub mod prepared;

pub use self::compressed::{
    GGLWECompressed, GGLWECompressedSeed, GGLWECompressedSeedMut, GGLWECompressedToBackendMut, GGLWECompressedToBackendRef,
    GGLWEDecompress, GGLWEToGGSWKeyCompressed, GGLWEToGGSWKeyCompressedToBackendMut, GGLWEToGGSWKeyCompressedToBackendRef,
    GGLWEToGGSWKeyDecompress, GGSWCompressed, GGSWCompressedSeed, GGSWCompressedSeedMut, GGSWCompressedToBackendMut,
    GGSWCompressedToBackendRef, GGSWDecompress, GLWEAutomorphismKeyCompressed, GLWEAutomorphismKeyDecompress, GLWECompressed,
    GLWECompressedSeed, GLWECompressedSeedMut, GLWECompressedToBackendMut, GLWECompressedToBackendRef, GLWEDecompress,
    GLWESwitchingKeyCompressed, GLWESwitchingKeyDecompress, GLWETensorKeyCompressed, GLWETensorKeyDecompress,
    GLWEToLWESwitchingKeyCompressed, GLWEToLWESwitchingKeyDecompress, LWECompressed, LWECompressedToBackendMut,
    LWECompressedToBackendRef, LWEDecompress, LWESwitchingKeyCompressed, LWESwitchingKeyDecompress, LWEToGLWEKeyCompressed,
    LWEToGLWEKeyDecompress,
};
pub use diagonals::*;
pub use gglwe::*;
pub use gglwe_to_ggsw_key::*;
pub use ggsw::*;
pub use glwe::*;
pub use glwe_automorphism_key::*;
pub use glwe_plaintext::*;
pub use glwe_public_key::*;
pub use glwe_secret::*;
pub use glwe_secret_tensor::*;
pub use glwe_switching_key::*;
pub use glwe_tensor::*;
pub use glwe_tensor_key::*;
pub use glwe_to_lwe_key::*;
pub use linear_transformation::*;
#[cfg(test)]
pub(crate) use linear_transformation::{linear_transformation_plan, normalize_linear_transform_diagonal};
pub use lwe::*;
pub use lwe_matrix::*;
pub use lwe_plaintext::*;
pub use lwe_secret::*;
pub use lwe_switching_key::*;
pub use lwe_to_glwe_key::*;
pub use polynomial_evaluation::*;
pub use prepared::*;
pub use scratch_views::*;

use crate::dist::Distribution;
use poulpy_hal::layouts::{Backend, Data, MatZnx, Module, ScalarZnx, VecZnx, ZnxWord};

/// Backend-indexed ownership aliases for the non-prepared layouts.
///
/// These resolve to `<Layout><<BE as Backend>::OwnedBuf>` so that user
/// code can declare types in terms of the owning backend instead of the
/// raw storage type. On CPU backends this is just `Vec<u8>`; on future
/// device backends it is the backend's device buffer type.
pub type BackendGLWE<BE> = GLWE<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendGGLWE<BE> = GGLWE<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendGGSW<BE> = GGSW<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendLWE<BE> = LWE<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendLWEMatrix<BE> = LWEMatrix<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendGLWESecret<BE> = GLWESecret<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendLWESecret<BE> = LWESecret<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendGLWEPlaintext<BE> = GLWEPlaintext<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendLWEPlaintext<BE> = LWEPlaintext<<BE as Backend>::OwnedBuf, <BE as Backend>::ZnxWord>;
pub type BackendGLWEPrepared<BE> = GLWEPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGGLWEPrepared<BE> = GGLWEPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGGSWPrepared<BE> = GGSWPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGLWESecretPrepared<BE> = GLWESecretPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGLWEPublicKeyPrepared<BE> = GLWEPublicKeyPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGLWESecretTensorPrepared<BE> = GLWESecretTensorPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGLWESwitchingKeyPrepared<BE> = GLWESwitchingKeyPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGLWEAutomorphismKeyPrepared<BE> = GLWEAutomorphismKeyPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGLWETensorKeyPrepared<BE> = GLWETensorKeyPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGLWEToLWEKeyPrepared<BE> = GLWEToLWEKeyPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendLWESwitchingKeyPrepared<BE> = LWESwitchingKeyPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendLWEToGLWEKeyPrepared<BE> = LWEToGLWEKeyPrepared<<BE as Backend>::OwnedBuf, BE>;
pub type BackendGGLWEToGGSWKeyPrepared<BE> = GGLWEToGGSWKeyPrepared<<BE as Backend>::OwnedBuf, BE>;

/// Provides access to the ring polynomial degree *N*.
pub trait GetDegree {
    /// Returns the ring degree *N* as a [`Degree`].
    fn ring_degree(&self) -> Degree;
}

impl<B: Backend> GetDegree for Module<B> {
    fn ring_degree(&self) -> Degree {
        Self::n(self).into()
    }
}

/// Backend-native wrapper allocation helpers hung off a [`Module`].
///
/// This mirrors the `poulpy-hal` allocation model: callers allocate through a
/// module/context object instead of using static layout constructors directly.
pub trait ModuleCoreAlloc {
    type OwnedBuf: Data;
    type ZnxWord: ZnxWord;

    fn glwe_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWE<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_alloc(&self, base2k: Base2K, k: TorusPrecision, rank: Rank) -> GLWE<Self::OwnedBuf, Self::ZnxWord>;

    /// Allocates a GLWE with exactly `size` limbs (so `max_size() == size`),
    /// labelling `k` as the full physical width `size · base2k`. Unlike
    /// [`Self::glwe_alloc`] (which derives `size = ceil(k / base2k)` from a target
    /// `k`), this takes the limb count directly, decoupling the buffer size from
    /// the effective `k` — relabel the effective `k` afterwards with [`SetK`].
    fn glwe_alloc_with_size(&self, base2k: Base2K, size: usize, rank: Rank) -> GLWE<Self::OwnedBuf, Self::ZnxWord>;

    fn gglwe_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GGLWE<Self::OwnedBuf, Self::ZnxWord>;
    fn gglwe_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GGLWE<Self::OwnedBuf, Self::ZnxWord>;

    fn ggsw_alloc_from_infos<A: GGSWInfos>(&self, infos: &A) -> GGSW<Self::OwnedBuf, Self::ZnxWord>;
    fn ggsw_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGSW<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_plaintext_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWEPlaintext<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_plaintext_alloc(&self, base2k: Base2K, k: TorusPrecision) -> GLWEPlaintext<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_secret_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWESecret<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_secret_alloc(&self, rank: Rank) -> GLWESecret<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_secret_tensor_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWESecretTensor<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_secret_tensor_alloc(&self, rank: Rank) -> GLWESecretTensor<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_tensor_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWETensor<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_tensor_alloc(&self, base2k: Base2K, k: TorusPrecision, rank: Rank) -> GLWETensor<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_public_key_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWEPublicKey<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_public_key_alloc(
        &self,
        base2k: Base2K,
        k: TorusPrecision,
        rank: Rank,
    ) -> GLWEPublicKey<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_switching_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GLWESwitchingKey<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_switching_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GLWESwitchingKey<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_automorphism_key_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWEAutomorphismKey<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_automorphism_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWEAutomorphismKey<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_tensor_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GLWETensorKey<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_tensor_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWETensorKey<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_to_lwe_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GLWEToLWEKey<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_to_lwe_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_in: Rank,
    ) -> GLWEToLWEKey<Self::OwnedBuf, Self::ZnxWord>;

    fn gglwe_to_ggsw_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GGLWEToGGSWKey<Self::OwnedBuf, Self::ZnxWord>;
    fn gglwe_to_ggsw_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGLWEToGGSWKey<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_alloc_from_infos<A: LWEInfos>(&self, infos: &A) -> LWE<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_alloc(&self, n: Degree, base2k: Base2K, k: TorusPrecision) -> LWE<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_matrix_alloc_from_infos<A: LWEMatrixInfos>(&self, infos: &A) -> LWEMatrix<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_matrix_alloc(
        &self,
        rows: usize,
        lwe_n: Degree,
        base2k: Base2K,
        k: TorusPrecision,
    ) -> LWEMatrix<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_plaintext_alloc_from_infos<A: LWEInfos>(&self, infos: &A) -> LWEPlaintext<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_plaintext_alloc(&self, base2k: Base2K, k: TorusPrecision) -> LWEPlaintext<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_secret_alloc(&self, n: Degree) -> LWESecret<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_switching_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> LWESwitchingKey<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_switching_key_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
    ) -> LWESwitchingKey<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_to_glwe_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> LWEToGLWEKey<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_to_glwe_key_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_out: Rank,
    ) -> LWEToGLWEKey<Self::OwnedBuf, Self::ZnxWord>;
}

impl<B: Backend> ModuleCoreAlloc for Module<B> {
    type OwnedBuf = B::OwnedBuf;
    type ZnxWord = B::ZnxWord;

    fn glwe_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWE<B::OwnedBuf, B::ZnxWord> {
        let size = infos.k().as_usize().div_ceil(infos.base2k().as_usize());
        GLWE {
            data: VecZnx::from_data(
                B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(infos.n().as_usize(), (infos.rank() + 1).as_usize(), size)),
                infos.n().as_usize(),
                (infos.rank() + 1).as_usize(),
                size,
            ),
            k: infos.k(),
            base2k: infos.base2k(),
        }
    }
    fn glwe_alloc(&self, base2k: Base2K, k: TorusPrecision, rank: Rank) -> GLWE<B::OwnedBuf, B::ZnxWord> {
        self.glwe_alloc_from_infos(&GLWELayout {
            n: self.ring_degree(),
            base2k,
            k,
            rank,
        })
    }

    fn glwe_alloc_with_size(&self, base2k: Base2K, size: usize, rank: Rank) -> GLWE<B::OwnedBuf, B::ZnxWord> {
        let n = self.ring_degree().as_usize();
        let cols = (rank + 1).as_usize();
        GLWE {
            data: VecZnx::from_data(B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(n, cols, size)), n, cols, size),
            k: TorusPrecision((size * base2k.as_usize()) as u32),
            base2k,
        }
    }

    fn gglwe_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GGLWE<B::OwnedBuf, B::ZnxWord> {
        let dnum = infos.dnum();
        let size = crate::layouts::key_size(infos.base2k(), dnum, infos.dsize(), infos.k_aux());

        GGLWE {
            data: MatZnx::from_data(
                B::alloc_zeroed_bytes(B::bytes_of_mat_znx(
                    infos.n().as_usize(),
                    dnum.as_usize(),
                    infos.rank_in().as_usize(),
                    (infos.rank_out() + 1).as_usize(),
                    size,
                )),
                infos.n().as_usize(),
                dnum.as_usize(),
                infos.rank_in().as_usize(),
                (infos.rank_out() + 1).as_usize(),
                size,
            ),
            k_aux: infos.k_aux(),
            base2k: infos.base2k(),
            dsize: infos.dsize(),
        }
    }
    fn gglwe_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GGLWE<B::OwnedBuf, B::ZnxWord> {
        self.gglwe_alloc_from_infos(&GGLWELayout {
            n: self.ring_degree(),
            base2k,
            dnum,
            dsize,
            k_aux,
            rank_in,
            rank_out,
        })
    }

    fn ggsw_alloc_from_infos<A: GGSWInfos>(&self, infos: &A) -> GGSW<B::OwnedBuf, B::ZnxWord> {
        let dnum = infos.dnum();
        let size = crate::layouts::key_size(infos.base2k(), dnum, infos.dsize(), infos.k_aux());

        GGSW {
            data: MatZnx::from_data(
                B::alloc_zeroed_bytes(B::bytes_of_mat_znx(
                    infos.n().as_usize(),
                    dnum.as_usize(),
                    (infos.rank() + 1).as_usize(),
                    (infos.rank() + 1).as_usize(),
                    size,
                )),
                infos.n().as_usize(),
                dnum.as_usize(),
                (infos.rank() + 1).as_usize(),
                (infos.rank() + 1).as_usize(),
                size,
            ),
            k_aux: infos.k_aux(),
            base2k: infos.base2k(),
            dsize: infos.dsize(),
        }
    }
    fn ggsw_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGSW<B::OwnedBuf, B::ZnxWord> {
        self.ggsw_alloc_from_infos(&GGSWLayout {
            n: self.ring_degree(),
            base2k,
            dnum,
            dsize,
            k_aux,
            rank,
        })
    }

    fn glwe_plaintext_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWEPlaintext<B::OwnedBuf, B::ZnxWord> {
        let size = infos.k().as_usize().div_ceil(infos.base2k().as_usize());
        GLWEPlaintext {
            data: VecZnx::from_data(
                B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(infos.n().as_usize(), 1, size)),
                infos.n().as_usize(),
                1,
                size,
            ),
            k: infos.k(),
            base2k: infos.base2k(),
        }
    }
    fn glwe_plaintext_alloc(&self, base2k: Base2K, k: TorusPrecision) -> GLWEPlaintext<B::OwnedBuf, B::ZnxWord> {
        self.glwe_plaintext_alloc_from_infos(&GLWEPlaintextLayout {
            n: self.ring_degree(),
            base2k,
            k,
        })
    }

    fn glwe_secret_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWESecret<B::OwnedBuf, B::ZnxWord> {
        GLWESecret {
            data: ScalarZnx::from_data(
                B::alloc_zeroed_bytes(B::bytes_of_scalar_znx(infos.n().as_usize(), infos.rank().as_usize())),
                infos.n().as_usize(),
                infos.rank().as_usize(),
            ),
            dist: Distribution::NONE,
        }
    }
    fn glwe_secret_alloc(&self, rank: Rank) -> GLWESecret<B::OwnedBuf, B::ZnxWord> {
        self.glwe_secret_alloc_from_infos(&GLWESecretLayout {
            n: self.ring_degree(),
            rank,
        })
    }

    fn glwe_secret_tensor_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWESecretTensor<B::OwnedBuf, B::ZnxWord> {
        let pairs = crate::layouts::pairs(infos.rank().as_usize());
        GLWESecretTensor {
            data: ScalarZnx::from_data(
                B::alloc_zeroed_bytes(B::bytes_of_scalar_znx(infos.n().as_usize(), pairs)),
                infos.n().as_usize(),
                pairs,
            ),
            rank: infos.rank(),
            dist: Distribution::NONE,
        }
    }
    fn glwe_secret_tensor_alloc(&self, rank: Rank) -> GLWESecretTensor<B::OwnedBuf, B::ZnxWord> {
        self.glwe_secret_tensor_alloc_from_infos(&GLWESecretLayout {
            n: self.ring_degree(),
            rank,
        })
    }

    fn glwe_tensor_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWETensor<B::OwnedBuf, B::ZnxWord> {
        let cols = infos.rank().as_usize() + 1;
        let pairs = (((cols + 1) * cols) >> 1).max(1);
        let size = infos.k().as_usize().div_ceil(infos.base2k().as_usize());
        GLWETensor {
            data: VecZnx::from_data(
                B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(infos.n().as_usize(), pairs, size)),
                infos.n().as_usize(),
                pairs,
                size,
            ),
            k: infos.k(),
            base2k: infos.base2k(),
            rank: infos.rank(),
        }
    }
    fn glwe_tensor_alloc(&self, base2k: Base2K, k: TorusPrecision, rank: Rank) -> GLWETensor<B::OwnedBuf, B::ZnxWord> {
        self.glwe_tensor_alloc_from_infos(&GLWELayout {
            n: self.ring_degree(),
            base2k,
            k,
            rank,
        })
    }

    fn glwe_public_key_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWEPublicKey<B::OwnedBuf, B::ZnxWord> {
        GLWEPublicKey {
            key: self.glwe_alloc_from_infos(infos),
            dist: Distribution::NONE,
        }
    }
    fn glwe_public_key_alloc(&self, base2k: Base2K, k: TorusPrecision, rank: Rank) -> GLWEPublicKey<B::OwnedBuf, B::ZnxWord> {
        self.glwe_public_key_alloc_from_infos(&GLWELayout {
            n: self.ring_degree(),
            base2k,
            k,
            rank,
        })
    }

    fn glwe_switching_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GLWESwitchingKey<B::OwnedBuf, B::ZnxWord> {
        GLWESwitchingKey {
            key: self.gglwe_alloc_from_infos(infos),
            input_degree: Degree(0),
            output_degree: Degree(0),
        }
    }
    fn glwe_switching_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GLWESwitchingKey<B::OwnedBuf, B::ZnxWord> {
        self.glwe_switching_key_alloc_from_infos(&GGLWELayout {
            n: self.ring_degree(),
            base2k,
            dnum,
            dsize,
            k_aux,
            rank_in,
            rank_out,
        })
    }

    fn glwe_automorphism_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GLWEAutomorphismKey<B::OwnedBuf, B::ZnxWord> {
        GLWEAutomorphismKey {
            key: self.gglwe_alloc_from_infos(infos),
            p: 0,
        }
    }
    fn glwe_automorphism_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWEAutomorphismKey<B::OwnedBuf, B::ZnxWord> {
        self.glwe_automorphism_key_alloc_from_infos(&GGLWELayout {
            n: self.ring_degree(),
            base2k,
            dnum,
            k_aux,
            rank_in: rank,
            rank_out: rank,
            dsize,
        })
    }

    fn glwe_tensor_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GLWETensorKey<B::OwnedBuf, B::ZnxWord> {
        GLWETensorKey(self.gglwe_alloc_from_infos(infos))
    }
    fn glwe_tensor_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWETensorKey<B::OwnedBuf, B::ZnxWord> {
        let pairs = (((rank.0 + 1) * rank.0) >> 1).max(1);
        self.glwe_tensor_key_alloc_from_infos(&GGLWELayout {
            n: self.ring_degree(),
            base2k,
            dnum,
            k_aux,
            rank_in: Rank(pairs),
            rank_out: rank,
            dsize,
        })
    }

    fn glwe_to_lwe_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GLWEToLWEKey<B::OwnedBuf, B::ZnxWord> {
        assert_eq!(infos.rank_out().0, 1, "rank_out > 1 is not supported for GLWEToLWEKey");
        assert_eq!(infos.dsize().0, 1, "dsize > 1 is not supported for GLWEToLWEKey");
        GLWEToLWEKey(self.glwe_switching_key_alloc_from_infos(infos))
    }
    fn glwe_to_lwe_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_in: Rank,
    ) -> GLWEToLWEKey<B::OwnedBuf, B::ZnxWord> {
        self.glwe_to_lwe_key_alloc_from_infos(&GGLWELayout {
            n: self.ring_degree(),
            base2k,
            dnum,
            k_aux,
            rank_in,
            rank_out: Rank(1),
            dsize: Dsize(1),
        })
    }

    fn gglwe_to_ggsw_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GGLWEToGGSWKey<B::OwnedBuf, B::ZnxWord> {
        assert_eq!(
            infos.rank_in(),
            infos.rank_out(),
            "rank_in != rank_out is not supported for GGLWEToGGSWKey"
        );
        GGLWEToGGSWKey {
            keys: (0..infos.rank().as_usize())
                .map(|_| self.gglwe_alloc_from_infos(infos))
                .collect(),
        }
    }
    fn gglwe_to_ggsw_key_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGLWEToGGSWKey<B::OwnedBuf, B::ZnxWord> {
        self.gglwe_to_ggsw_key_alloc_from_infos(&GGLWELayout {
            n: self.ring_degree(),
            base2k,
            dnum,
            k_aux,
            rank_in: rank,
            rank_out: rank,
            dsize,
        })
    }

    fn lwe_alloc_from_infos<A: LWEInfos>(&self, infos: &A) -> LWE<B::OwnedBuf, B::ZnxWord> {
        let size = infos.k().as_usize().div_ceil(infos.base2k().as_usize());
        let n = infos.n().as_usize();
        LWE {
            body: VecZnx::from_data(B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(1, 1, size)), 1, 1, size),
            mask: VecZnx::from_data(B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(n, 1, size)), n, 1, size),
            base2k: infos.base2k(),
            k: infos.k(),
        }
    }
    fn lwe_alloc(&self, n: Degree, base2k: Base2K, k: TorusPrecision) -> LWE<B::OwnedBuf, B::ZnxWord> {
        self.lwe_alloc_from_infos(&LWELayout { n, base2k, k })
    }

    fn lwe_matrix_alloc_from_infos<A: LWEMatrixInfos>(&self, infos: &A) -> LWEMatrix<B::OwnedBuf, B::ZnxWord> {
        let size = infos.k().as_usize().div_ceil(infos.base2k().as_usize());
        let rows = infos.rows();
        LWEMatrix {
            body: VecZnx::from_data(B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(rows, 1, size)), rows, 1, size),
            mask: VecZnx::from_data(
                B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(rows, infos.n().as_usize(), size)),
                rows,
                infos.n().as_usize(),
                size,
            ),
            k: infos.k(),
            base2k: infos.base2k(),
        }
    }
    fn lwe_matrix_alloc(
        &self,
        rows: usize,
        lwe_n: Degree,
        base2k: Base2K,
        k: TorusPrecision,
    ) -> LWEMatrix<B::OwnedBuf, B::ZnxWord> {
        self.lwe_matrix_alloc_from_infos(&LWEMatrixLayout {
            rows,
            n: lwe_n,
            base2k,
            k,
        })
    }

    fn lwe_plaintext_alloc_from_infos<A: LWEInfos>(&self, infos: &A) -> LWEPlaintext<B::OwnedBuf, B::ZnxWord> {
        let size = infos.k().as_usize().div_ceil(infos.base2k().as_usize());
        LWEPlaintext {
            data: VecZnx::from_data(B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(1, 1, size)), 1, 1, size),
            k: infos.k(),
            base2k: infos.base2k(),
        }
    }
    fn lwe_plaintext_alloc(&self, base2k: Base2K, k: TorusPrecision) -> LWEPlaintext<B::OwnedBuf, B::ZnxWord> {
        let size = k.as_usize().div_ceil(base2k.as_usize());
        LWEPlaintext {
            data: VecZnx::from_data(B::alloc_zeroed_bytes(self.bytes_of_vec_znx_n(1, 1, size)), 1, 1, size),
            k,
            base2k,
        }
    }

    fn lwe_secret_alloc(&self, n: Degree) -> LWESecret<B::OwnedBuf, B::ZnxWord> {
        LWESecret {
            data: ScalarZnx::from_data(
                B::alloc_zeroed_bytes(B::bytes_of_scalar_znx(n.as_usize(), 1)),
                n.as_usize(),
                1,
            ),
            dist: Distribution::NONE,
        }
    }

    fn lwe_switching_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> LWESwitchingKey<B::OwnedBuf, B::ZnxWord> {
        assert_eq!(infos.dsize().0, 1, "dsize > 1 is not supported for LWESwitchingKey");
        assert_eq!(infos.rank_in().0, 1, "rank_in > 1 is not supported for LWESwitchingKey");
        assert_eq!(infos.rank_out().0, 1, "rank_out > 1 is not supported for LWESwitchingKey");
        LWESwitchingKey(self.glwe_switching_key_alloc_from_infos(infos))
    }
    fn lwe_switching_key_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
    ) -> LWESwitchingKey<B::OwnedBuf, B::ZnxWord> {
        self.lwe_switching_key_alloc_from_infos(&LWESwitchingKeyLayout { n, base2k, dnum, k_aux })
    }

    fn lwe_to_glwe_key_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> LWEToGLWEKey<B::OwnedBuf, B::ZnxWord> {
        assert_eq!(infos.rank_in().0, 1, "rank_in > 1 is not supported for LWEToGLWEKey");
        assert_eq!(infos.dsize().0, 1, "dsize > 1 is not supported for LWEToGLWEKey");
        LWEToGLWEKey(self.glwe_switching_key_alloc_from_infos(infos))
    }
    fn lwe_to_glwe_key_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_out: Rank,
    ) -> LWEToGLWEKey<B::OwnedBuf, B::ZnxWord> {
        self.lwe_to_glwe_key_alloc_from_infos(&GGLWELayout {
            n,
            base2k,
            dnum,
            k_aux,
            rank_in: Rank(1),
            rank_out,
            dsize: Dsize(1),
        })
    }
}

/// Host-owned compressed wrapper allocation helpers hung off a [`Module`].
///
/// This mirrors [`ModuleCoreAlloc`], but for seed-compressed ciphertext and
/// key layouts.
pub trait ModuleCoreCompressedAlloc {
    type OwnedBuf: Data;
    type ZnxWord: ZnxWord;

    fn glwe_compressed_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWECompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_compressed_alloc(
        &self,
        base2k: Base2K,
        k: TorusPrecision,
        rank: Rank,
    ) -> GLWECompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_compressed_alloc_from_infos<A: LWEInfos>(&self, infos: &A) -> LWECompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_compressed_alloc(&self, base2k: Base2K, k: TorusPrecision) -> LWECompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn gglwe_compressed_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GGLWECompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn gglwe_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GGLWECompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn ggsw_compressed_alloc_from_infos<A: GGSWInfos>(&self, infos: &A) -> GGSWCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn ggsw_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGSWCompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_switching_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWESwitchingKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_switching_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GLWESwitchingKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_automorphism_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWEAutomorphismKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_automorphism_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWEAutomorphismKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_tensor_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWETensorKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_tensor_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWETensorKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn glwe_to_lwe_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWEToLWESwitchingKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn glwe_to_lwe_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_in: Rank,
    ) -> GLWEToLWESwitchingKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_to_glwe_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> LWEToGLWEKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_to_glwe_key_compressed_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_out: Rank,
    ) -> LWEToGLWEKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn lwe_switching_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> LWESwitchingKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn lwe_switching_key_compressed_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
    ) -> LWESwitchingKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;

    fn gglwe_to_ggsw_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GGLWEToGGSWKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
    fn gglwe_to_ggsw_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGLWEToGGSWKeyCompressed<Self::OwnedBuf, Self::ZnxWord>;
}

impl<B: Backend> ModuleCoreCompressedAlloc for Module<B> {
    type OwnedBuf = B::OwnedBuf;
    type ZnxWord = B::ZnxWord;
    fn glwe_compressed_alloc_from_infos<A: GLWEInfos>(&self, infos: &A) -> GLWECompressed<B::OwnedBuf, B::ZnxWord> {
        GLWECompressed::alloc_from_infos::<B, _>(infos)
    }
    fn glwe_compressed_alloc(&self, base2k: Base2K, k: TorusPrecision, rank: Rank) -> GLWECompressed<B::OwnedBuf, B::ZnxWord> {
        GLWECompressed::alloc::<B>(self.ring_degree(), base2k, k, rank)
    }

    fn lwe_compressed_alloc_from_infos<A: LWEInfos>(&self, infos: &A) -> LWECompressed<B::OwnedBuf, B::ZnxWord> {
        LWECompressed::alloc_from_infos::<B, _>(infos)
    }
    fn lwe_compressed_alloc(&self, base2k: Base2K, k: TorusPrecision) -> LWECompressed<B::OwnedBuf, B::ZnxWord> {
        LWECompressed::alloc::<B>(base2k, k)
    }

    fn gglwe_compressed_alloc_from_infos<A: GGLWEInfos>(&self, infos: &A) -> GGLWECompressed<B::OwnedBuf, B::ZnxWord> {
        GGLWECompressed::alloc_from_infos::<B, _>(infos)
    }
    fn gglwe_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GGLWECompressed<B::OwnedBuf, B::ZnxWord> {
        GGLWECompressed::alloc::<B>(self.ring_degree(), base2k, dnum, dsize, k_aux, rank_in, rank_out)
    }

    fn ggsw_compressed_alloc_from_infos<A: GGSWInfos>(&self, infos: &A) -> GGSWCompressed<B::OwnedBuf, B::ZnxWord> {
        GGSWCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn ggsw_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGSWCompressed<B::OwnedBuf, B::ZnxWord> {
        GGSWCompressed::alloc::<B>(self.ring_degree(), base2k, dnum, dsize, k_aux, rank)
    }

    fn glwe_switching_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWESwitchingKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWESwitchingKeyCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn glwe_switching_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank_in: Rank,
        rank_out: Rank,
    ) -> GLWESwitchingKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWESwitchingKeyCompressed::alloc::<B>(self.ring_degree(), base2k, dnum, dsize, k_aux, rank_in, rank_out)
    }

    fn glwe_automorphism_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWEAutomorphismKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWEAutomorphismKeyCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn glwe_automorphism_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWEAutomorphismKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWEAutomorphismKeyCompressed::alloc::<B>(self.ring_degree(), base2k, dnum, dsize, k_aux, rank)
    }

    fn glwe_tensor_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWETensorKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWETensorKeyCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn glwe_tensor_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GLWETensorKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWETensorKeyCompressed::alloc::<B>(self.ring_degree(), base2k, dnum, dsize, k_aux, rank)
    }

    fn glwe_to_lwe_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GLWEToLWESwitchingKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWEToLWESwitchingKeyCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn glwe_to_lwe_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_in: Rank,
    ) -> GLWEToLWESwitchingKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GLWEToLWESwitchingKeyCompressed::alloc::<B>(self.ring_degree(), base2k, dnum, k_aux, rank_in)
    }

    fn lwe_to_glwe_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> LWEToGLWEKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        LWEToGLWEKeyCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn lwe_to_glwe_key_compressed_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
        rank_out: Rank,
    ) -> LWEToGLWEKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        LWEToGLWEKeyCompressed::alloc::<B>(n, base2k, dnum, k_aux, rank_out)
    }

    fn lwe_switching_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> LWESwitchingKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        LWESwitchingKeyCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn lwe_switching_key_compressed_alloc(
        &self,
        n: Degree,
        base2k: Base2K,
        dnum: Dnum,
        k_aux: TorusPrecision,
    ) -> LWESwitchingKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        LWESwitchingKeyCompressed::alloc::<B>(n, base2k, dnum, k_aux)
    }

    fn gglwe_to_ggsw_key_compressed_alloc_from_infos<A: GGLWEInfos>(
        &self,
        infos: &A,
    ) -> GGLWEToGGSWKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GGLWEToGGSWKeyCompressed::alloc_from_infos::<B, _>(infos)
    }
    fn gglwe_to_ggsw_key_compressed_alloc(
        &self,
        base2k: Base2K,
        dnum: Dnum,
        dsize: Dsize,
        k_aux: TorusPrecision,
        rank: Rank,
    ) -> GGLWEToGGSWKeyCompressed<B::OwnedBuf, B::ZnxWord> {
        GGLWEToGGSWKeyCompressed::alloc::<B>(self.ring_degree(), base2k, dnum, dsize, k_aux, rank)
    }
}

/// Newtype over `u32` with arithmetic and comparisons against same type and `u32`.
/// Arithmetic is **saturating** (add/sub/mul) to avoid debug-overflow panics.
macro_rules! newtype_u32 {
    ($(#[$meta:meta])* $name:ident) => {
        $(#[$meta])*
        #[repr(transparent)]
        #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
        pub struct $name(pub u32);

        // ----- Conversions -----
        impl From<$name> for u32 {
            #[inline]
            fn from(v: $name) -> u32 {
                v.0
            }
        }
        impl From<$name> for usize {
            #[inline]
            fn from(v: $name) -> usize {
                v.0 as usize
            }
        }

        impl From<u32> for $name {
            #[inline]
            fn from(v: u32) -> $name {
                $name(v)
            }
        }
        impl From<usize> for $name {
            #[inline]
            fn from(v: usize) -> $name {
                debug_assert!(v <= u32::MAX as usize, "{} overflow: {v} > u32::MAX", stringify!($name));
                $name(v as u32)
            }
        }

        // ----- Display -----
        impl ::core::fmt::Display for $name {
            #[inline]
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                write!(f, "{}", self.0)
            }
        }

        // ===== Arithmetic (same type) =====
        impl ::core::ops::Add for $name {
            type Output = $name;
            #[inline]
            fn add(self, rhs: $name) -> $name {
                $name(self.0.saturating_add(rhs.0))
            }
        }
        impl ::core::ops::Sub for $name {
            type Output = $name;
            #[inline]
            fn sub(self, rhs: $name) -> $name {
                $name(self.0.saturating_sub(rhs.0))
            }
        }
        impl ::core::ops::Mul for $name {
            type Output = $name;
            #[inline]
            fn mul(self, rhs: $name) -> $name {
                $name(self.0.saturating_mul(rhs.0))
            }
        }

        // ===== Arithmetic (with u32) =====
        impl ::core::ops::Add<u32> for $name {
            type Output = $name;
            #[inline]
            fn add(self, rhs: u32) -> $name {
                $name(self.0.saturating_add(rhs))
            }
        }
        impl ::core::ops::Sub<u32> for $name {
            type Output = $name;
            #[inline]
            fn sub(self, rhs: u32) -> $name {
                $name(self.0.saturating_sub(rhs))
            }
        }
        impl ::core::ops::Mul<u32> for $name {
            type Output = $name;
            #[inline]
            fn mul(self, rhs: u32) -> $name {
                $name(self.0.saturating_mul(rhs))
            }
        }

        impl $name {
            #[inline]
            pub const fn as_u32(self) -> u32 {
                self.0
            }
            #[inline]
            pub const fn as_usize(self) -> usize {
                self.0 as usize
            }

            #[inline]
            pub fn div_ceil<T: Into<u32>>(self, rhs: T) -> u32 {
                self.0.div_ceil(rhs.into())
            }
        }

        // Optional symmetric forms: u32 (+|-|*) $name -> $name
        impl ::core::ops::Add<$name> for u32 {
            type Output = $name;
            #[inline]
            fn add(self, rhs: $name) -> $name {
                $name(self.saturating_add(rhs.0))
            }
        }
        impl ::core::ops::Sub<$name> for u32 {
            type Output = $name;
            #[inline]
            fn sub(self, rhs: $name) -> $name {
                $name(self.saturating_sub(rhs.0))
            }
        }
        impl ::core::ops::Mul<$name> for u32 {
            type Output = $name;
            #[inline]
            fn mul(self, rhs: $name) -> $name {
                $name(self.saturating_mul(rhs.0))
            }
        }

        // ===== Cross-type comparisons with u32 (both directions) =====
        impl ::core::cmp::PartialEq<u32> for $name {
            #[inline]
            fn eq(&self, other: &u32) -> bool {
                self.0 == *other
            }
        }
        impl ::core::cmp::PartialEq<$name> for u32 {
            #[inline]
            fn eq(&self, other: &$name) -> bool {
                *self == other.0
            }
        }

        impl ::core::cmp::PartialOrd<u32> for $name {
            #[inline]
            fn partial_cmp(&self, other: &u32) -> Option<::core::cmp::Ordering> {
                self.0.partial_cmp(other)
            }
        }
        impl ::core::cmp::PartialOrd<$name> for u32 {
            #[inline]
            fn partial_cmp(&self, other: &$name) -> Option<::core::cmp::Ordering> {
                self.partial_cmp(&other.0)
            }
        }
    };
}

newtype_u32!(
    /// Ring polynomial degree *N* (always a power of two).
    ///
    /// Wraps a [`u32`] with saturating arithmetic.
    Degree
);

newtype_u32!(
    /// Torus precision in bits — the total number of significant bits
    /// used to represent elements of the discretised torus *T = R/Z*.
    ///
    /// Wraps a [`u32`] with saturating arithmetic.
    TorusPrecision
);

newtype_u32!(
    /// Base-2 logarithm of the limb radix in the digit (CRT)
    /// decomposition of ciphertext coefficients.
    ///
    /// Coefficients are stored as `ceil(k / base2k)` limbs, each
    /// carrying `base2k` bits of precision.
    ///
    /// Wraps a [`u32`] with saturating arithmetic.
    Base2K
);

newtype_u32!(
    /// Number of gadget-decomposition digits used in GGLWE / GGSW
    /// ciphertexts.
    ///
    /// Wraps a [`u32`] with saturating arithmetic.
    Dnum
);

newtype_u32!(
    /// GLWE rank — the number of mask polynomials in a GLWE ciphertext.
    ///
    /// A rank-0 GLWE is equivalent to a plain LWE ciphertext.
    ///
    /// Wraps a [`u32`] with saturating arithmetic.
    Rank
);

newtype_u32!(
    /// Size (in limbs) of each gadget-decomposition digit.
    ///
    /// Wraps a [`u32`] with saturating arithmetic.
    Dsize
);

impl Degree {
    /// Returns log2(n). Assumes n is a positive power of two.
    pub fn log2(&self) -> usize {
        debug_assert!(
            self.0 > 0 && self.0.is_power_of_two(),
            "Degree::log2 requires a positive power of two, got {}",
            self.0
        );
        self.0.trailing_zeros() as usize
    }
}

/// Total torus precision of a key: `dnum * dsize * base2k + k_aux`, i.e. the
/// gadget precision (`dnum` digits of `dsize` limbs at radix `base2k`) plus the
/// auxiliary guard region `k_aux`. This is what `LWEInfos::k()` reports for the
/// GGLWE/GGSW key families, so encryption places the error at the physical
/// bottom limb.
pub fn key_k(base2k: Base2K, dnum: Dnum, dsize: Dsize, k_aux: TorusPrecision) -> TorusPrecision {
    debug_assert!(
        k_aux.0 >= dsize.0 * base2k.0,
        "k_aux ({}) must be at least dsize * base2k ({} * {} = {}): the auxiliary guard must \
         cover at least one full gadget digit, otherwise operations truncate mid-digit",
        k_aux.0,
        dsize.0,
        base2k.0,
        dsize.0 * base2k.0
    );
    TorusPrecision(dnum.0 * dsize.0 * base2k.0 + k_aux.0)
}

/// Number of limbs stored per row of a key: `ceil((dnum*dsize*base2k + k_aux) / base2k)`,
/// i.e. the `dnum * dsize` gadget limbs plus `ceil(k_aux / base2k)` auxiliary
/// (guard) limbs used for noise management.
pub fn key_size(base2k: Base2K, dnum: Dnum, dsize: Dsize, k_aux: TorusPrecision) -> usize {
    key_k(base2k, dnum, dsize, k_aux).0.div_ceil(base2k.0) as usize
}

/// Number of key limbs an operation should process for an input ciphertext of
/// precision `input_k` (clamped to the key size by callers). Replaces the old
/// explicit `key_size`/`tsk_size` argument.
///
/// The gadget is consumed in whole digits of `dsize` limbs each, so the region
/// covering `input_k` must be rounded up to a digit boundary — truncating
/// mid-digit would drop a gadget row entirely and wreck the decomposition.
/// The auxiliary guard `k_aux` then adds `ceil(k_aux / base2k)` limbs on top:
///
/// ```text
/// digits = ceil(input_k / (dsize * base2k))
/// work   = digits * dsize + ceil(k_aux / base2k)
/// ```
pub fn key_work_size(base2k: Base2K, input_k: TorusPrecision, dsize: Dsize, k_aux: TorusPrecision) -> usize {
    let digit_bits: u32 = dsize.0 * base2k.0;
    let digits: u32 = input_k.0.div_ceil(digit_bits);
    (digits * dsize.0 + k_aux.0.div_ceil(base2k.0)) as usize
}

/// Narrows [`key_work_size`] to the limbs that can affect an immediately
/// normalized product. Exact same-radix arithmetic can discard the distant
/// guard-region tail; other arithmetic retains the complete work region.
pub(crate) fn gadget_product_output_size(
    work_size: usize,
    input_size: usize,
    output_size: usize,
    base2k: Base2K,
    exact_same_radix: bool,
    term_count: usize,
) -> usize {
    if !exact_same_radix {
        return work_size;
    }

    let carry_bits = if term_count <= 1 {
        0
    } else {
        usize::BITS as usize - (term_count - 1).leading_zeros() as usize
    };
    let carry_limbs = carry_bits.div_ceil(base2k.as_usize());
    work_size.min(input_size.max(output_size).saturating_add(2).saturating_add(carry_limbs))
}

#[cfg(test)]
mod gadget_sizing_tests {
    use super::*;

    #[test]
    fn work_size_rounds_input_to_a_whole_digit_before_aux_limbs() {
        // Two 2-limb digits plus two auxiliary limbs.
        assert_eq!(key_work_size(Base2K(30), TorusPrecision(61), Dsize(2), TorusPrecision(31)), 6);
    }

    #[test]
    fn output_size_is_a_second_stage_bounded_by_work_size() {
        assert_eq!(gadget_product_output_size(12, 3, 4, Base2K(30), true, 1), 6);
        assert_eq!(gadget_product_output_size(5, 3, 4, Base2K(30), true, 1), 5);
        assert_eq!(gadget_product_output_size(12, 3, 4, Base2K(30), false, 1), 12);
        assert_eq!(gadget_product_output_size(12, 3, 4, Base2K(1), true, 5), 9);
    }
}
