//! Shared skeleton of the two carry-verb families (add, sub).
//!
//! [`CKKSAddReference`](crate::reference::CKKSAddReference) and
//! [`CKKSSubReference`](crate::reference::CKKSSubReference) are exact mirrors: same operand alignment, same metadata stamping, same plaintext facades — only the core GLWE verb and its coefficient-wise HAL hooks differ.
//! The [`ckks_carry_verb_reference!`] macro generates both traits from one body so the mirrors cannot drift (the pre-macro hand-written copies had already diverged on the tmp-bytes formulas and error labels).
//!
//! The macro is `pub(crate)`: it is an implementation detail of the two verb modules, not a backend-facing extension point.

use crate::CKKSResult as Result;
use crate::layouts::CKKSPlaintextOwned;
use poulpy_core::layouts::IntPolyInfos;
use poulpy_core::layouts::{Base2K, GLWEPlaintext};
use poulpy_hal::layouts::Backend;

use crate::SlotsKind;
use crate::{
    CKKSMeta, SetCKKSInfos,
    layouts::{CKKSModuleAlloc, CKKSPlaintext},
};

/// Builds the backend-resident constant-`1.0` plaintext used by the
/// add-one/sub-one facades.
///
/// This currently allocates and uploads a degree-1, single-limb monomial on
/// each call. The unit-operation scratch query covers the arithmetic workspace.
pub(crate) fn ckks_one_pt<BE, M>(module: &M, base2k: Base2K) -> Result<CKKSPlaintextOwned<BE>>
where
    BE: Backend,
    M: CKKSModuleAlloc<BE> + ?Sized,
{
    let meta = CKKSMeta {
        log_sparsity: 0,
        log_delta: 1,
        slots: SlotsKind::Real,
    };

    // Monomial plaintext: total torus width is `log_delta` (budget 0).
    let k_total: usize = meta.log_delta;

    // The constant is integer-exact: 1.0 at scale `2^log_delta` is the single
    // coefficient `1 << log_delta`, so the limb bytes are built with the integer
    // codec and uploaded as raw bytes — no float codec or backend transfer op.
    let mut host_pt =
        CKKSPlaintext::<_, _, BE::Ring>::from_inner(GLWEPlaintext::alloc_with_meta(1usize.into(), base2k, k_total.into()), meta);
    let max_k = host_pt.encoded_k();
    host_pt.encode_vec_i64(&[1i64 << meta.log_delta], max_k);

    let mut pt = module.ckks_pt_coeffs_alloc(1, base2k, k_total.into());
    pt.set_meta(meta);
    pt.copy_from_host_bytes::<BE>(host_pt.data().data().as_slice());
    Ok(pt)
}

/// Generates a `CKKS{Add,Sub}Reference` trait: the full reference-layer carry-verb
/// family (ct–ct, ct–pt-vector, ct–pt-constant, plus the one-constant
/// facades and the tmp-bytes accounting). None of them normalizes the result.
///
/// Parameters:
/// - `verb`: method-name stem (`add` / `sub`), also the error label.
/// - `doc_verb`: human verb for generated docs (`"addition"` / `"subtraction"`).
/// - `trait_name`: generated trait identifier.
/// - `glwe_bound` / `glwe_into` / `glwe_assign` / `glwe_lsh_verb`: the core
///   GLWE verb trait and its into/assign/shift-accumulate methods.
/// - `pt_vec_bounds`: the verb-specific HAL shift backend traits (each takes
///   a `<BE>` parameter), shared by the pt-vector and pt-constant variants.
///
/// All type and trait names in the expansion resolve at the call site: the
/// invoking module must import the shared bounds (`GLWECopy`, `GLWEShift`, `GLWENormalize`,
/// `VecZnx{Lsh,Rsh}TmpBytes`, `CKKSPlaintextReference`, `CKKSModuleAlloc`, the
/// info traits) alongside its verb-specific ones.
macro_rules! ckks_carry_verb_reference {
    (
        verb: $verb:ident,
        doc_verb: $doc_verb:literal,
        trait_name: $Trait:ident,
        glwe_bound: $GLWEVerb:ident,
        glwe_into: $glwe_into:ident,
        glwe_assign: $glwe_assign:ident,
        glwe_lsh_verb: $glwe_lsh_verb:ident,
        pt_vec_bounds: [$($PtVecBound:ident),+ $(,)?],
    ) => {
        ::paste::paste! {
            #[doc = concat!("Backend-generic reference implementation of the CKKS ", $doc_verb, " family.")]
            #[doc = ""]
            #[doc = "Generated by `ckks_carry_verb_reference!` — the add and sub families share one body (see `reference::carry_verb`)."]
            pub trait $Trait<BE: Backend> {
                /// Scratch bytes for the ct–ct variants.
                ///
                /// The three tmp-bytes methods share one formula: the max over the
                /// GLWE shift, GLWE normalize, and coefficient-wise `vec_znx` shift
                /// scratch needs. The ct–ct path never touches the `vec_znx` hooks,
                /// so for it this is a slight over-provision — the price of keeping
                /// one formula for the whole family.
                fn [<ckks_ $verb _tmp_bytes_reference>](&self, res_size: usize) -> usize
                where
                    Self: GLWEShift<BE> + GLWENormalize<BE> + VecZnxLshTmpBytes + VecZnxRshTmpBytes,
                {
                    self.glwe_shift_tmp_bytes(res_size)
                        .max(self.glwe_normalize_tmp_bytes())
                        .max(self.vec_znx_rsh_tmp_bytes(res_size))
                        .max(self.vec_znx_lsh_tmp_bytes(res_size))
                }

                /// Scratch bytes for the ct–pt-vector variants.
                fn [<ckks_ $verb _pt_vec_tmp_bytes_reference>](&self, res_size: usize) -> usize
                where
                    Self: GLWEShift<BE> + GLWENormalize<BE> + VecZnxLshTmpBytes + VecZnxRshTmpBytes,
                {
                    self.[<ckks_ $verb _tmp_bytes_reference>](res_size)
                }

                /// Scratch bytes for the ct–pt-constant variants.
                fn [<ckks_ $verb _pt_const_tmp_bytes_reference>](&self, res_size: usize) -> usize
                where
                    Self: GLWEShift<BE> + GLWENormalize<BE> + VecZnxLshTmpBytes + VecZnxRshTmpBytes,
                {
                    self.[<ckks_ $verb _tmp_bytes_reference>](res_size)
                }

                fn [<ckks_ $verb _into_reference>]<Dst, A, B>(
                    &self,
                    dst: &mut Dst,
                    a: &A,
                    b: &B,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Self: $GLWEVerb<BE> + GLWEShift<BE>,
                    Dst: GLWEToBackendMut<BE> + LWEInfos + SetCKKSInfos + CKKSInfos,
                    A: GLWEToBackendRef<BE> + CKKSInfos,
                    B: GLWEToBackendRef<BE> + CKKSInfos,
                {
                    let offset = ckks_offset_binary(dst, a, b);
                    // Validate before mutating: on error `dst` must remain untouched.
                    let log_budget =
                        checked_log_budget_sub(stringify!($verb), a.log_budget().min(b.log_budget()), offset)?;

                    // Align both operands to the common torus level: operand `x` is
                    // shifted by `x.log_budget − min_budget + offset`. When both
                    // shifts are zero and `dst` holds both operands' limbs, the
                    // plain verb applies directly.
                    let min_budget = a.log_budget().min(b.log_budget());
                    let shift_a = a.log_budget() - min_budget + offset;
                    let shift_b = b.log_budget() - min_budget + offset;
                    if shift_a == 0 && shift_b == 0 && $crate::ckks_holds_limbs(dst, a) && $crate::ckks_holds_limbs(dst, b) {
                        self.$glwe_into(dst, a, b);
                    } else {
                        self.glwe_lsh(dst, a, shift_a, scratch);
                        self.$glwe_lsh_verb(dst, b, shift_b, scratch);
                    }

                    dst.set_log_delta(a.log_delta().min(b.log_delta()));
                    dst.set_log_budget(log_budget);
                    // The sum/product of values sparse at `s` and `t` is sparse at `min(s, t)`.
                    dst.set_log_sparsity(a.log_sparsity().min(b.log_sparsity()));
                    dst.set_slots(a.slots().join(b.slots()));
                    Ok(())
                }

                fn [<ckks_ $verb _assign_reference>]<Dst, A>(
                    &self,
                    dst: &mut Dst,
                    a: &A,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Self: $GLWEVerb<BE> + GLWEShift<BE>,
                    Dst: GLWEToBackendMut<BE> + CKKSInfos + SetCKKSInfos,
                    A: GLWEToBackendRef<BE> + CKKSInfos,
                {
                    let dst_log_budget = dst.log_budget();

                    if dst_log_budget > a.log_budget() {
                        self.glwe_lsh_assign(dst, dst_log_budget - a.log_budget(), scratch);
                    }
                    let shift_a = a.log_budget().saturating_sub(dst_log_budget);
                    // The shift-accumulate normalizes `a` over all its limbs.
                    if shift_a == 0 && $crate::ckks_holds_limbs(dst, a) {
                        self.$glwe_assign(dst, a);
                    } else {
                        self.$glwe_lsh_verb(dst, a, shift_a, scratch);
                    }

                    dst.set_log_budget(dst_log_budget.min(a.log_budget()));
                    dst.set_log_delta(dst.log_delta().min(a.log_delta()));
                    // The sum/product of values sparse at `s` and `t` is sparse at `min(s, t)`.
                    dst.set_log_sparsity(dst.log_sparsity().min(a.log_sparsity()));
                    dst.set_slots(dst.slots().join(a.slots()));
                    Ok(())
                }

                fn [<ckks_ $verb _pt_vec_into_reference>]<Dst, A, P>(
                    &self,
                    dst: &mut Dst,
                    a: &A,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Self: GLWECopy<BE> + GLWEShift<BE> $(+ $PtVecBound<BE>)+ + CKKSPlaintextReference<BE>,
                    Dst: GLWEToBackendMut<BE> + CKKSInfos + SetCKKSInfos,
                    A: GLWEToBackendRef<BE> + CKKSInfos,
                    P: GLWEToBackendRef<BE> + ::poulpy_core::layouts::IntPolyInfos + CKKSInfos,
                {
                    $crate::ckks_copy_stamp_unary(self, concat!(stringify!($verb), "_pt_vec"), dst, a, scratch)?;
                    self.[<ckks_ $verb _pt_vec_assign_reference>](dst, pt, scratch)
                }

                fn [<ckks_ $verb _pt_vec_assign_reference>]<Dst, P>(
                    &self,
                    dst: &mut Dst,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Self: CKKSPlaintextReference<BE> $(+ $PtVecBound<BE>)+,
                    Dst: GLWEToBackendMut<BE> + CKKSInfos + SetCKKSInfos,
                    P: GLWEToBackendRef<BE> + ::poulpy_core::layouts::IntPolyInfos + CKKSInfos,
                {
                    CKKSPlaintextReference::[<ckks_ $verb _pt_vec_into_reference>](self, dst, pt, scratch)?;
                    dst.set_slots(dst.slots().join(pt.slots()));
                    Ok(())
                }

                fn [<ckks_ $verb _pt_const_into_reference>]<Dst, A, P>(
                    &self,
                    dst: &mut Dst,
                    a: &A,
                    dst_coeff: usize,
                    cst: &P,
                    const_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Self: GLWECopy<BE> + GLWEShift<BE> $(+ $PtVecBound<BE>)+ + CKKSPlaintextReference<BE>,
                    Dst: GLWEToBackendMut<BE> + CKKSInfos + SetCKKSInfos,
                    A: GLWEToBackendRef<BE> + CKKSInfos,
                    P: GLWEToBackendRef<BE> + ::poulpy_core::layouts::IntPolyInfos + CKKSInfos,
                {
                    $crate::ckks_copy_stamp_unary(self, concat!(stringify!($verb), "_pt_const"), dst, a, scratch)?;
                    self.[<ckks_ $verb _pt_const_assign_reference>](dst, dst_coeff, cst, const_coeff, scratch)
                }

                fn [<ckks_ $verb _pt_const_assign_reference>]<Dst, P>(
                    &self,
                    dst: &mut Dst,
                    dst_coeff: usize,
                    cst: &P,
                    const_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Self: CKKSPlaintextReference<BE> $(+ $PtVecBound<BE>)+,
                    Dst: GLWEToBackendMut<BE> + CKKSInfos + SetCKKSInfos,
                    P: GLWEToBackendRef<BE> + ::poulpy_core::layouts::IntPolyInfos + CKKSInfos,
                {
                    CKKSPlaintextReference::[<ckks_ $verb _pt_const_into_reference>](self, dst, dst_coeff, cst, const_coeff, scratch)?;
                    // cst is always tagged as real, it's where dst_coeff lands
                    // that selects if the added constant is real (X^{0}) or imaginary (X^{N/2}).
                    let added = if dst_coeff == 0 { $crate::SlotsKind::Real } else { $crate::SlotsKind::Complex };
                    dst.set_slots(dst.slots().join(added));
                    Ok(())
                }
            }
        }
    };
}
pub(crate) use ckks_carry_verb_reference;
