//! Shared skeleton of the two carry-verb OEP seams (add, sub).
//!
//! [`CKKSAddImpl`](crate::oep::CKKSAddImpl) and [`CKKSSubImpl`](crate::oep::CKKSSubImpl) are pure forwarding mirrors: every method delegates to the matching `CKKS{Add,Sub}Default` method, unwrapping the unnormalized wrapper types where needed.
//! The [`ckks_carry_verb_oep!`] macro generates both traits and their blanket impls from one body so the mirrors cannot drift (the pre-macro copies had diverged: sub lacked the `_assign_unnormalized_ref_impl` variant).
//!
//! The per-verb `impl_ckks_{add,sub}_defaults!` backend-wiring macros stay in their verb modules — they are the exported surface, this macro is `pub(crate)`.

/// Generates a `CKKS{Add,Sub}Impl` OEP trait and its blanket impl forwarding
/// to the verb's `CKKS{Add,Sub}Default` reference implementation.
///
/// Parameters mirror [`ckks_carry_verb_default!`](crate::default::carry_verb::ckks_carry_verb_default):
/// the verb stem, the generated trait name, the default trait to forward to,
/// the core GLWE verb bound, and the verb-specific coefficient-wise HAL bounds
/// (needed by the blanket impl's where-clause).
///
/// Names in the expansion resolve at the call site: the invoking module must
/// import the shared bounds and wrapper types (`GLWENormalize`, `GLWEShift`,
/// `VecZnx{Lsh,Rsh}TmpBytes`, `CKKSPlaintextDefault`, `CKKSModuleAlloc`,
/// `UnnormalizedCKKSCiphertext[RefMut]`, `CKKSCiphertext`, `GLWE`) alongside
/// its verb-specific ones.
macro_rules! ckks_carry_verb_oep {
    (
        verb: $verb:ident,
        doc_verb: $doc_verb:literal,
        impl_trait: $Impl:ident,
        default_trait: $Default:ident,
        glwe_bound: $GLWEVerb:ident,
        pt_vec_bounds: [$($PtVecBound:ident),+ $(,)?],
        pt_const_bounds: [$($PtConstBound:ident),+ $(,)?],
    ) => {
        ::paste::paste! {
            #[doc = concat!("Backend override seam for the CKKS ", $doc_verb, " family.")]
            #[doc = ""]
            #[doc = "Generated by `ckks_carry_verb_oep!` — the add and sub seams share one body (see `oep::carry_verb`)."]
            #[doc = ""]
            /// # Safety
            ///
            /// Implementations must satisfy the contracts of all trait methods, including
            /// any HAL-level invariants (alignment, layout, scratch sizing) implied by the
            /// associated method signatures.
            pub unsafe trait $Impl<BE: Backend>: Backend {
                fn [<ckks_ $verb _tmp_bytes_impl>](module: &Module<BE>) -> usize;
                fn [<ckks_ $verb _into_impl>]<Dst, A, B>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    b: &B,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    B: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds;
                fn [<ckks_ $verb _into_unnormalized_impl>]<Dst, A, B>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    b: &B,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    B: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds;
                fn [<ckks_ $verb _assign_impl>]<Dst, A>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos;
                fn [<ckks_ $verb _assign_unnormalized_impl>]<Dst, A>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos;
                /// Crate-internal accumulator seam: like the `_assign_unnormalized`
                /// variant, but on an [`UnnormalizedCKKSCiphertextRefMut`] reborrow of a
                /// caller-owned normalized ciphertext. Deliberately has **no api
                /// counterpart**: the reborrow type is unconstructible outside the
                /// crate (see its docs), so an api method taking it would be
                /// uncallable — and a public constructor would void the `CoeffNormalized`
                /// type guard. Consumed by the composite dot-product accumulators.
                fn [<ckks_ $verb _assign_unnormalized_ref_impl>]<Dst, A>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertextRefMut<'_, Dst, BE::ZnxWord>,
                    a: &A,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    CKKSCiphertext<Dst, BE::ZnxWord>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos;
                fn [<ckks_ $verb _one_assign_impl>]<Dst>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos;
                fn [<ckks_ $verb _pt_vec_tmp_bytes_impl>](module: &Module<BE>) -> usize;
                fn [<ckks_ $verb _pt_vec_into_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_vec_into_unnormalized_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_vec_assign_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_vec_assign_unnormalized_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_tmp_bytes_impl>](module: &Module<BE>) -> usize;
                fn [<ckks_ $verb _pt_const_into_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_into_unnormalized_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_assign_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_assign_unnormalized_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
            }

            unsafe impl<BE: Backend> $Impl<BE> for BE
            where
                BE: ::poulpy_hal::oep::HalVecZnxImpl<BE>,
                Module<BE>: $Default<BE>
                    + CKKSModuleAlloc<BE>
                    + CKKSPlaintextDefault<BE>
                    + $GLWEVerb<BE>
                    + GLWENormalize<BE>
                    + GLWEShift<BE>
                    $(+ $PtVecBound<BE>)+
                    $(+ $PtConstBound<BE>)+
                    + VecZnxLshTmpBytes
                    + VecZnxRshTmpBytes,
            {
                fn [<ckks_ $verb _tmp_bytes_impl>](module: &Module<BE>) -> usize {
                    $Default::[<ckks_ $verb _tmp_bytes_default>](module)
                }

                fn [<ckks_ $verb _into_impl>]<Dst, A, B>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    b: &B,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    B: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                {
                    $Default::[<ckks_ $verb _into_default>](module, dst, a, b, scratch)
                }

                fn [<ckks_ $verb _into_unnormalized_impl>]<Dst, A, B>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    b: &B,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    B: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                {
                    $Default::[<ckks_ $verb _into_unnormalized_default>](module, dst, a, b, scratch)
                }

                fn [<ckks_ $verb _assign_impl>]<Dst, A>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos,
                {
                    $Default::[<ckks_ $verb _assign_default>](module, dst, a, scratch)
                }

                fn [<ckks_ $verb _assign_unnormalized_impl>]<Dst, A>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos,
                {
                    $Default::[<ckks_ $verb _assign_unnormalized_default>](module, dst, a, scratch)
                }

                fn [<ckks_ $verb _assign_unnormalized_ref_impl>]<Dst, A>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertextRefMut<'_, Dst, BE::ZnxWord>,
                    a: &A,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    CKKSCiphertext<Dst, BE::ZnxWord>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSInfos,
                {
                    $Default::[<ckks_ $verb _assign_unnormalized_default>](
                        module,
                        &mut $crate::layouts::ciphertext::CKKSUnnormalizedWriteView::new(dst.inner),
                        a,
                        scratch,
                    )
                }

                fn [<ckks_ $verb _one_assign_impl>]<Dst>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                {
                    $Default::[<ckks_ $verb _one_assign_default>](module, dst, scratch)
                }

                fn [<ckks_ $verb _pt_vec_tmp_bytes_impl>](module: &Module<BE>) -> usize {
                    $Default::[<ckks_ $verb _pt_vec_tmp_bytes_default>](module)
                }

                fn [<ckks_ $verb _pt_vec_into_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_vec_into_default>](module, dst, a, pt, scratch)
                }

                fn [<ckks_ $verb _pt_vec_into_unnormalized_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_vec_into_unnormalized_default>](module, dst, a, pt, scratch)
                }

                fn [<ckks_ $verb _pt_vec_assign_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_vec_assign_default>](module, dst, pt, scratch)
                }

                fn [<ckks_ $verb _pt_vec_assign_unnormalized_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_vec_assign_unnormalized_default>](module, dst, pt, scratch)
                }

                fn [<ckks_ $verb _pt_const_tmp_bytes_impl>](module: &Module<BE>) -> usize {
                    $Default::[<ckks_ $verb _pt_const_tmp_bytes_default>](module)
                }

                fn [<ckks_ $verb _pt_const_into_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    a: &A,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_const_into_default>](module, dst, a, dst_coeff, pt, pt_coeff, scratch)
                }

                fn [<ckks_ $verb _pt_const_into_unnormalized_impl>]<Dst, A, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    a: &A,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    A: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_const_into_unnormalized_default>](
                        module,
                        dst,
                        a,
                        dst_coeff,
                        pt,
                        pt_coeff,
                        scratch,
                    )
                }

                fn [<ckks_ $verb _pt_const_assign_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut Dst,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + SetCKKSInfos,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_const_assign_default>](module, dst, dst_coeff, pt, pt_coeff, scratch)
                }

                fn [<ckks_ $verb _pt_const_assign_unnormalized_impl>]<Dst, P>(
                    module: &Module<BE>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, BE::ZnxWord>,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, BE>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, BE::ZnxWord, ::poulpy_hal::layouts::CoeffUnnormalized>: GLWEToBackendMut<BE, State = ::poulpy_hal::layouts::CoeffUnnormalized>,
                    P: GLWEToBackendRef<BE, State = ::poulpy_hal::layouts::CoeffNormalized> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos,
                {
                    $Default::[<ckks_ $verb _pt_const_assign_unnormalized_default>](
                        module,
                        dst,
                        dst_coeff,
                        pt,
                        pt_coeff,
                        scratch,
                    )
                }
            }
        }
    };
}
pub(crate) use ckks_carry_verb_oep;
