//! Shared add/sub backend contract declarations.
//!
//! Reference wiring remains in the corresponding family modules. Unnormalized
//! wrappers are unwrapped inside the reference layer, keeping their internal
//! mutable views private.

macro_rules! ckks_carry_verb_oep {
    (
        verb: $verb:ident,
        doc_verb: $doc_verb:literal,
        impl_trait: $Impl:ident,
    ) => {
        ::paste::paste! {
            #[doc = concat!("Backend override seam for the CKKS ", $doc_verb, " family.")]
            #[doc = ""]
            #[doc = "Generated by `ckks_carry_verb_oep!` — the add and sub seams share one body (see `oep::carry_verb`)."]
            #[doc = ""]
            /// # Safety
            ///
            /// Implementations must satisfy the contracts of all trait methods, including
            /// any HAL-level invariants (alignment, layout, scratch sizing) implied by the
            /// associated method signatures.
            pub unsafe trait $Impl: Backend {
                fn [<ckks_ $verb _tmp_bytes_impl>](module: &Module<Self>, res_size: usize) -> usize;
                fn [<ckks_ $verb _into_impl>]<Dst, A, B>(
                    module: &Module<Self>,
                    dst: &mut Dst,
                    a: &A,
                    b: &B,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<Self> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<Self> + CKKSCtBounds,
                    B: GLWEToBackendRef<Self> + CKKSCtBounds;
                fn [<ckks_ $verb _into_unnormalized_impl>]<Dst, A, B>(
                    module: &Module<Self>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, Self::ZnxWord>,
                    a: &A,
                    b: &B,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, Self::ZnxWord>: GLWEToBackendMut<Self>,
                    A: GLWEToBackendRef<Self> + CKKSCtBounds,
                    B: GLWEToBackendRef<Self> + CKKSCtBounds;
                fn [<ckks_ $verb _assign_impl>]<Dst, A>(
                    module: &Module<Self>,
                    dst: &mut Dst,
                    a: &A,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<Self> + CKKSInfos + SetCKKSInfos,
                    A: GLWEToBackendRef<Self> + CKKSInfos;
                fn [<ckks_ $verb _assign_unnormalized_impl>]<Dst, A>(
                    module: &Module<Self>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, Self::ZnxWord>,
                    a: &A,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, Self::ZnxWord>: GLWEToBackendMut<Self>,
                    A: GLWEToBackendRef<Self> + CKKSInfos;
                /// Crate-internal accumulator seam: like the `_assign_unnormalized`
                /// variant, but on an [`UnnormalizedCKKSCiphertextRefMut`] reborrow of a
                /// caller-owned normalized ciphertext. Deliberately has **no api
                /// counterpart**: the reborrow type is unconstructible outside the
                /// crate (see its docs), so an api method taking it would be
                /// uncallable — and a public constructor would void the `Normalized`
                /// type guard. Consumed by the composite dot-product accumulators.
                fn [<ckks_ $verb _assign_unnormalized_ref_impl>]<Dst, A>(
                    module: &Module<Self>,
                    dst: &mut UnnormalizedCKKSCiphertextRefMut<'_, Dst, Self::ZnxWord>,
                    a: &A,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: Data,
                    CKKSCiphertext<Dst, Self::ZnxWord>: GLWEToBackendMut<Self>,
                    A: GLWEToBackendRef<Self> + CKKSInfos;
                fn [<ckks_ $verb _one_assign_impl>]<Dst>(
                    module: &Module<Self>,
                    dst: &mut Dst,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<Self> + CKKSCtBounds + SetCKKSInfos {
                    crate::oep::derived::carry_verb::[<ckks_ $verb _one_assign_derived>](module, dst, scratch)
                }
                fn [<ckks_ $verb _pt_vec_tmp_bytes_impl>](module: &Module<Self>, res_size: usize) -> usize;
                fn [<ckks_ $verb _pt_vec_into_impl>]<Dst, A, P>(
                    module: &Module<Self>,
                    dst: &mut Dst,
                    a: &A,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<Self> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<Self> + CKKSCtBounds,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_vec_into_unnormalized_impl>]<Dst, A, P>(
                    module: &Module<Self>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, Self::ZnxWord>,
                    a: &A,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, Self::ZnxWord>: GLWEToBackendMut<Self>,
                    A: GLWEToBackendRef<Self> + CKKSCtBounds,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_vec_assign_impl>]<Dst, P>(
                    module: &Module<Self>,
                    dst: &mut Dst,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<Self> + CKKSCtBounds + SetCKKSInfos,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_vec_assign_unnormalized_impl>]<Dst, P>(
                    module: &Module<Self>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, Self::ZnxWord>,
                    pt: &P,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, Self::ZnxWord>: GLWEToBackendMut<Self>,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_tmp_bytes_impl>](module: &Module<Self>, res_size: usize) -> usize;
                fn [<ckks_ $verb _pt_const_into_impl>]<Dst, A, P>(
                    module: &Module<Self>,
                    dst: &mut Dst,
                    a: &A,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<Self> + CKKSCtBounds + SetCKKSInfos,
                    A: GLWEToBackendRef<Self> + CKKSCtBounds,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_into_unnormalized_impl>]<Dst, A, P>(
                    module: &Module<Self>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, Self::ZnxWord>,
                    a: &A,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, Self::ZnxWord>: GLWEToBackendMut<Self>,
                    A: GLWEToBackendRef<Self> + CKKSCtBounds,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_assign_impl>]<Dst, P>(
                    module: &Module<Self>,
                    dst: &mut Dst,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: GLWEToBackendMut<Self> + CKKSCtBounds + SetCKKSInfos,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
                fn [<ckks_ $verb _pt_const_assign_unnormalized_impl>]<Dst, P>(
                    module: &Module<Self>,
                    dst: &mut UnnormalizedCKKSCiphertext<Dst, Self::ZnxWord>,
                    dst_coeff: usize,
                    pt: &P,
                    pt_coeff: usize,
                    scratch: &mut ScratchArena<'_, Self>,
                ) -> Result<()>
                where
                    Dst: Data,
                    GLWE<Dst, Self::ZnxWord>: GLWEToBackendMut<Self>,
                    P: GLWEToBackendRef<Self> + CKKSCtBounds + ::poulpy_core::layouts::IntPolyInfos;
            }


        }
    };
}
pub(crate) use ckks_carry_verb_oep;
