[package]
name = "poulpy-cpu-ref"
version = "0.7.0"
edition = "2024"
license = "Apache-2.0"
readme = "README.md"
description = "Portable reference CPU implementations of poulpy-hal open extension points"
repository = "https://github.com/poulpy-fhe/poulpy"
homepage = "https://github.com/poulpy-fhe/poulpy"
documentation = "https://docs.rs/poulpy-cpu-ref"

[features]
enable-core = []
enable-ckks = ["dep:poulpy-ckks", "enable-core"]

[dependencies]
anyhow = {workspace = true}
poulpy-ckks = {workspace = true, optional = true}
poulpy-core = {workspace = true}
poulpy-hal = {workspace = true}
#poulpy-bench = {workspace = true}
dashu-float = {workspace = true}
bytemuck = {workspace = true}
itertools = {workspace = true}
rand = {workspace = true}
rand_distr = {workspace = true}
rand_core = {workspace = true}
byteorder = {workspace = true}
once_cell = {workspace = true}
rand_chacha = {workspace = true}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "bootstrap_trace"
required-features = ["enable-ckks"]

[[example]]
name = "ckks_poly2"
required-features = ["enable-ckks"]

[[example]]
name = "ckks_hello"
required-features = ["enable-ckks"]

[[example]]
name = "core_encryption"
required-features = ["enable-core"]

[dev-dependencies]
poulpy-ckks = {workspace = true, features = ["test-utils"]}
poulpy-bin-fhe = {workspace = true}
criterion = {workspace = true}
# TODO: poulpy-bench's lib is currently #![cfg]-gated on its bench features
poulpy-bench = {workspace = true} #  features = ["hal-bench", "bin-fhe-bench", "ckks-bench", "core-bench"]

[[bench]]
name = "full"
harness = false
required-features = ["enable-core", "enable-ckks"]

[[bench]]
name = "standard"
harness = false
required-features = ["enable-core", "enable-ckks"]

[[bench]]
name = "light"
harness = false
required-features = ["enable-core", "enable-ckks"]